version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /curiosity
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /xtask
    schedule:
        interval: daily
  - package-ecosystem: npm
    directory: /curiosity
    schedule:
        interval: daily