tasks:
  - init: |
      rustup update
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      rustup component add clippy rustfmt --toolchain nightly
      curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
    command: cargo build --release --target wasm32-wasi
