name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  push:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - wasm32-unknown-unknown
          - wasm32-wasi
    steps:
      - uses: actions/checkout@v3
      - name: rustup
        run: |
          rustup default nightly
          rustup target add ${{ matrix.target }} --toolchain nightly
      - run: cargo build --release -v --target ${{ matrix.target }}
  publish:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    # needs: sdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (curiosity)
        run: cargo publish --all-features -v -p curiosity --token ${{ secrets.CARGO_REGISTRY_TOKEN }}